name: zizmor

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  scan-workflows:
    name: Scan workflows
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@v0.6.4
